"""
Turn hard-sample manifests into review action suggestions.

Outputs per group:
- action_summary.json
- relabel_candidates.csv
- ambiguous_candidates.csv
- general_review.csv
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path


DEFAULT_GROUP_THRESHOLDS = {
    "plant": {
        "relabel_conf": 0.82,
        "relabel_margin": 0.18,
        "ambiguous_conf": 0.58,
        "ambiguous_margin": 0.08,
    },
    "door": {
        "relabel_conf": 0.80,
        "relabel_margin": 0.16,
        "ambiguous_conf": 0.60,
        "ambiguous_margin": 0.10,
    },
    "window": {
        "relabel_conf": 0.80,
        "relabel_margin": 0.16,
        "ambiguous_conf": 0.60,
        "ambiguous_margin": 0.10,
    },
    "table": {
        "relabel_conf": 0.88,
        "relabel_margin": 0.22,
        "ambiguous_conf": 0.60,
        "ambiguous_margin": 0.08,
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Suggest relabel/review actions from hard-sample manifests.")
    parser.add_argument("--review-root", default="review_manifests", help="Root generated by mine_hard_samples.py")
    parser.add_argument("--group", nargs="+", help="Groups to process. Default processes all groups present.")
    return parser.parse_args()


def selected_groups(args: argparse.Namespace, review_root: Path) -> list[str]:
    if args.group:
        return args.group
    return sorted(path.name for path in review_root.iterdir() if path.is_dir())


def parse_float(value: str) -> float:
    try:
        return float(value)
    except Exception:
        return 0.0


def classify_row(group: str, row: dict[str, str]) -> str:
    conf = parse_float(row["confidence"])
    margin = parse_float(row["margin"])
    error = row["error"] == "1"
    thresholds = DEFAULT_GROUP_THRESHOLDS.get(group, DEFAULT_GROUP_THRESHOLDS["door"])

    if error and conf >= thresholds["relabel_conf"] and margin >= thresholds["relabel_margin"]:
        return "relabel_candidate"
    if error and conf <= thresholds["ambiguous_conf"] and margin <= thresholds["ambiguous_margin"]:
        return "ambiguous_candidate"
    return "general_review"


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = [
        "path",
        "split",
        "true_label",
        "pred_label",
        "confidence",
        "margin",
        "error",
        "reasons",
        "suggested_action",
    ]
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def process_group(review_root: Path, group: str) -> dict[str, object]:
    source_csv = review_root / group / "hard_samples.csv"
    if not source_csv.exists():
        raise FileNotFoundError(f"Missing hard sample file for group {group}: {source_csv}")

    relabel_rows: list[dict[str, str]] = []
    ambiguous_rows: list[dict[str, str]] = []
    general_rows: list[dict[str, str]] = []

    with source_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for raw in reader:
            action = classify_row(group, raw)
            row = dict(raw)
            row["suggested_action"] = action
            if action == "relabel_candidate":
                relabel_rows.append(row)
            elif action == "ambiguous_candidate":
                ambiguous_rows.append(row)
            else:
                general_rows.append(row)

    out_root = review_root / group / "actions"
    write_csv(out_root / "relabel_candidates.csv", relabel_rows)
    write_csv(out_root / "ambiguous_candidates.csv", ambiguous_rows)
    write_csv(out_root / "general_review.csv", general_rows)

    relabel_pairs = Counter(f"{row['true_label']}->{row['pred_label']}" for row in relabel_rows)
    ambiguous_pairs = Counter(f"{row['true_label']}->{row['pred_label']}" for row in ambiguous_rows if row["error"] == "1")

    summary = {
        "group": group,
        "source_csv": str(source_csv.resolve()),
        "counts": {
            "relabel_candidate": len(relabel_rows),
            "ambiguous_candidate": len(ambiguous_rows),
            "general_review": len(general_rows),
        },
        "top_relabel_pairs": dict(relabel_pairs.most_common(10)),
        "top_ambiguous_pairs": dict(ambiguous_pairs.most_common(10)),
    }
    (out_root / "action_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return summary


def main(args: argparse.Namespace) -> None:
    review_root = Path(args.review_root)
    groups = selected_groups(args, review_root)
    summary = {}
    for group in groups:
        summary[group] = process_group(review_root, group)
    (review_root / "action_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[done] action suggestions written to: {review_root.resolve()}")


if __name__ == "__main__":
    main(parse_args())
